# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4a2272e81a6847123419e26bf164c62e1045f6e6b0f66123281fb5cdee8bfefe0fd1c66e349f63b4daea902ae6b3670cd716c8107e714b3fdb57e3e6f757847

test:
  secret_key_base: 11c70be57726e4217377dec2841964172273a4f35251b0f8465adf70997d90ca82cf4f33046cdd64c225419edfb6ee98284bc866d7bcc10ebdd9c5941653f05c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
